### ISSUE TITLE
Crash when logging/printing Unicode symbols

### ISSUE THREAD

**Issue by Filnor** [SOBotics/CheckYerFlags#5]
The bot crashed multiple times in public testing in the SOBotics chat. This error is either caused by printing the messages with `print(message)`.  
There are now three possibilities I could think of to resolve this issue:
- **Don't use Unicode:** The worst attempt, as bots like Heat Detector use Unicode in their messages.
- **Don't log/print the messages to chat:** The currently active solution, but more a quick and dirty solution than a real fix.
- **Implement Unicode handling:** I never did that and don't know how it actually works and how to implement it. *Information and guidance about this solution is appreciated!*

Steps to find the issue cause: uncomment the two lines above and check which one of the both is causing the error.

**Comment by Filnor** [comment]
It should be possible to solve the issue with [this answer](https://stackoverflow.com/a/2365444):
```
u'aあä'.encode('ascii', 'ignore')
```

**Comment by adeak** [comment]
Your links aren't pointing to specific commits and now the code is different. Was it [this](https://github.com/SOBotics/FlaggersHall/blob/2053a148bcc15df596e25a569b2acef40a8eab6d/chat.py#L43) and [this](https://github.com/SOBotics/FlaggersHall/blob/2053a148bcc15df596e25a569b2acef40a8eab6d/chat.py#L47) line? Neither look like something that should cause a crash. Any relevant error messages and tracebacks from the crash? This (including ChatExchange) is python 3, right?

**Comment by Filnor** [comment]
@adeak 

> Your links aren't pointing to specific commits and now the code is different.

I removed those lines in the meantime, hoping that it would resolve the issue (it didn't). I've updated the issue description.

> Any relevant error messages and tracebacks from the crash?

The error I recieve on the crash is a `UnicodeDecodeError`.
Funny enough, when running the development version on Windows machine, there are no problems, but when I run the bot on my server (Ubuntu 16.04 command-line) it crashes on unicode symbols ([example](https://chat.stackoverflow.com/rooms/163468/conversation/how-to-crash-the-bot)).

> This (including ChatExchange) is python 3, right?

Yes, it's Python 3 code running on 3.6.1 (Windows) on my dev machine and running 3.5.2 on the productive server. IIRC, ChatExchange is cross-version, so it should be compatible with Python 3.

**Comment by adeak** [comment]
So are you sure your ubuntu server is actually running python 3? You should make sure; from what I could quickly find these problems usually arise on python 2 (from, say, using `""` byte format strings with `u""` unicode-string stuff to put inside). In the mean time, could you point me to the two lines in a commit where they were still there...? Edit: please see [mcve] etc ;)

**Comment by adeak** [comment]
Ah, I just noticed you mention that you updated the issue. `print(message)` especially shouldn't break anything. So I'd definitely like to see a full commit which produced the problem. Thanks.

**Comment by Filnor** [comment]
Yes I'm completely sure I'm running Python3 (I start the bot with `python3 chat.py`). Those lines were commented out [in this commit](https://github.com/SOBotics/FlaggersHall/commit/03c331814ff58835821a9edff00ec21948ac8ce2#diff-7a9543fbd76d3ca5f7dc0f6bbc9dd3cb) and [this is the full file at this revision](https://github.com/SOBotics/FlaggersHall/blob/03c331814ff58835821a9edff00ec21948ac8ce2/chat.py). Interesting is, that when I change this snippet:

```python
elif messagecompare.compareMessage(message_val, "say"):
        print(message)
        room = client.get_room(room_id)
        room.send_message(message.content.split('say', 1)[1])
```
to 
```python
elif messagecompare.compareMessage(message_val, "say"):
        print(message.content.encode('ascii', 'ignore'))
        room = client.get_room(room_id)
        room.send_message(message.content.split('say', 1)[1])
```
it works. I'm still wondering why this works and why it doesn't break at `compareMessage()` (one of my functions) and at `romm.send_message()` (a ChatExchange function).  
My guess is that the encoding is messing things up, for whatever reason the files are saved (and therefore run) as ANSI (blame JetBrains/IntelliJ IDEA for that).

I guess it's worth a try to re-encode everthing to UTF-8.
Otherwise, the workaround like in the above snippet should also do it.

**Comment by adeak** [comment]
So, this is really weird. All the lines which seem to raise are where `message` gets `repr`ed (the logging line) or `str`ed (the print lines). This should _not_ break anything; on python 3 chatexchange should by all means use (unicode) strings by default, and the format strings should also be the same. As a last resort you could try `print(repr(message))` alone, but I don't see a custom `__repr__` nor `__str__` in ChatExchange. This is all just weird.

So, I'd first make sure that everything is updated (BeautifulSoup, for starters, which `message.content` ultimately comes from). And try printing just `message.content` rather than `message`. But I don't think `repr(message)` should crash under any circumstances.

Well, but now I see that you're working with a `MessageEvent` instance (rather than a `Message` instance?), which _does_ have [a custom `__repr__`](https://github.com/Manishearth/ChatExchange/blob/ddaaed56b47fddd0988ecc4fe5903d9714aa28f2/chatexchange/events.py#L62-L64). But that looks safe to me too. I can't really figure out the relationship between `Message`s and `MessageEvent`s. This probably doesn't help at all.

Anyway, if you could post a full traceback, that might help too, although if it indeed was just `print(message)`, it probably won't.

**Comment by Filnor** [comment]
The discussion continued in the [chatroom, where we found a solution](https://chat.stackoverflow.com/rooms/163468/conversation/resolve-the-bot-crashes). The fix will be added in the next commit.
